### ISSUE TITLE
Poll for people already gave up supporting IE11

### ISSUE THREAD

**Issue by motss** [gabLaroche/death-to-ie11#1]
It'd be great to see a list of websites, people, or even companies that are no longer supporting IE11. I could see more and more large companies stop supporting that browser recently.

**Comment by gabLaroche** [comment]
That's a good idea, I'll look into it and try to find that Data

**Comment by gabLaroche** [comment]
I added a JSON with a list of websites, there are only two websites so far, feel free to contribute

**Comment by gabLaroche** [comment]
For now we only have Dev.to and my Website,  it would be nice to have more websites

**Comment by motss** [comment]
GitHub also stop supporting IE11.
