### ISSUE TITLE
EOL for Windows 10 got extended

### ISSUE THREAD

**Issue by marcelammerlaan** [gabLaroche/death-to-ie11#13]
**Describe the bug**
The current counter shows 6 years until IE11 dies. The EOL page for Windows 10 (https://support.microsoft.com/en-ca/lifecycle/search?alpha=Windows%2010) gives 2029-01-09 as the last date. So it should be closer to 9 years (unfortunately).

**To Reproduce**
1. Go to https://death-to-ie11.netlify.com/
2. Click on 'nothing'
3. Scroll down to 'not needed'
4. See error: '6 Years'

**Additional context**
Although LTSC is not the norm for Windows 10 users, it does exist and does include IE11. Maybe add a disclaimer that MS is making a mess of their EOL policy and you should actually measure IE usage (as I see it's already becoming irrelevant for some of my customers, for others not so).

**Comment by gabLaroche** [comment]
Added a disclaimer, and made it clear that this is not an official countdown
