### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bmcallis** [gabLaroche/death-to-ie11#23]
https://github.com/gabLaroche/death-to-ie11/blob/099d79975ef46b0ad2c714ffe4ee6a2914fd04d3/src/index.html#L41

`:s/tou/you`

**Comment by gabLaroche** [comment]
Oops! Will fix, thanks for pointing this out!

**Comment by gabLaroche** [comment]
Fixed with this commit: https://github.com/gabLaroche/death-to-ie11/commit/65b2f309691db54b705eb6bd25c00b618ea7eafc
