### ISSUE TITLE
Add twitter in who stopped IE11 section.

### ISSUE THREAD

**Issue by swarad07** [gabLaroche/death-to-ie11#28]
**Is your feature request related to a problem? Please describe.**
Twitter is a one of the largest sites by active users and has stopped supporting IE11 in its June 2, 2020 release. This should be mentioned on the site.
https://twitter.com/i/release_notes

**Describe the solution you'd like**
Add twitter in  `Who stopped supporting IE11`.

**Comment by gabLaroche** [comment]
https://github.com/gabLaroche/death-to-ie11/commit/f48e1a4bb4e8fbc72b879314085fdd4e4b654bd4
