### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by gabLaroche** [gabLaroche/death-to-ie11#38]
I am no designer, but I know that the design for the website is terrible and I don;t know how to fix it. I am open to suggestions and design submissions.

**Comment by faisaljamil25** [comment]
Can I work on this?

**Comment by gabLaroche** [comment]
@faisaljamil25 Yes

**Comment by thesanjeevsharma** [comment]
@gabLaroche I would like to work on this.

**Comment by lucid-dreem** [comment]
I could help out as well

**Comment by gabLaroche** [comment]
@thesanjeevsharma and @lucid-dreem your help is more than welcome! The more eyes on this, the better

**Comment by Octateam** [comment]
Hello @gabLaroche I would like to help out on this project too

**Comment by gabLaroche** [comment]
@Octateam Yes! thank you for your interest! I assigned the ticket to you

**Comment by gabLaroche** [comment]
@faisaljamil25 @lucid-dreem @Octateam There was a PR submitted for this issue (#41) I will let you continue work on this until the 31st of October, if no new design is submitted, I will merge #41 and close this issue. Thank you all for your interest in this project and this particular issue
