### ISSUE TITLE
Your source for end of support is wrong

### ISSUE THREAD

**Issue by p91paul** [gabLaroche/death-to-ie11#54]
You claim "I got the data from windows 10 end of support documentation".
However, under the current policy, Windows 10 is never going do be EOL.
They are going to continue releasing new versions every 6 months that will extend the current EOL.
Unless a major change in the Windows release model is presented, your date is, unfortunately, based on constantly outdated data.
The current mainstream end of support is 10/05/2022 (in 2 years rather than 4 months, see https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro, reachable from your own link), and is going to be extended in a matter of weeks as 2021H1 is nearing release. 
A more accurate description would be "I got the data from what I wish will happen"

Also, for related reasons, the second link in your Why section (https://www.swyx.io/ie11-eol/) claims that Windows 10 support ended six months ago (I quote: "mainstream support for Windows 10 ends on Oct 13 2020"), which would mean Microsoft is no longer a PC operating system vendor as they have no alternatives outside the server space. While that would be really nice, it's really not what happened.

**Comment by gabLaroche** [comment]
You're right. There is no official EOL for IE11, and my sources are a little all over the place and unclear. I am working on a redesign and a rewrite of the copy to make it clear that the number is arbitrary and that the goal of the website is more to inform people that they don't have to support IE11 before the (fake) clock runs out.

**Comment by gabLaroche** [comment]
Well Microsoft just announced that they will retire IE11 next year. I updated the website and added the [source](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/). good thing I wasn't done on my redesign then.
